name: Build Release
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 18
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Start build
              run: pnpm build

            - name: Zip .next folder
              run: zip -r default.next.zip .next
            
            - name: Upload as release
              run: |
                gh release upload build default.next.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}